### ISSUE TITLE
Readme example

### ISSUE THREAD

**Issue by AlexsJones** [emreodabas/kubectl-plugins#7]
Hello,

It is not clear to me in the example what this is for.

`kubectl bulk deploy -n test get image `

Is this doing a get on the CRD type of deploy? As deploy is not a kubectl command I think there could be a more beginner friendly example.

My expectation is I could use this tool to do something like:

`kubectl bulk svc --all-namespaces` 

In which case where is the value add over get?

As you can see I could use some guidance. Thank you!

**Comment by emreodabas** [comment]
Hi Alex, 

Thank you for your feedbacks,
 I updated some of samples to not using short names of resources(deploy-> deployment), as you said It could be seems unfamiliar to beginner.

 Bulk plugin's first statement is about resource that working on it, you could think there is a hidden get for that resources. You could use most of the "kubectl get"  arguments for filtering or sorting resources. For example you could use --all-namespaces (-A),   or -namespace(-n)  tag on bulk command.  I added one sample for "get" data. After selecting your resource you could get|list|create|update|delete|remove|rollout of related resources with some related arguments. I personally try to simplify as much as possible. I am ready to hear ideas for simplifying plugin or new features.  
   
 I personally use to edit some attributes of  my deployments in one command and replicating deployments or namespaces for testing purposes. 

I hope it is more clear for you too. Also thanks for my very first issue :D

**Comment by AlexsJones** [comment]
Hey Thanks @emreodabas I appreciate you taking the time to update the samples. I'm going to check them out now 👍 your explanation also makes it much clearer! :)
